global:
  # resolve_timeout is the time after which an alert is declared resolved
  resolve_timeout: 1m

  # incoming-webhook API auth for "gravity-testnet-monitoring" channel
  # gravity-dex-monitoring
  slack_api_url: "https://hooks.slack.com/services/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"
  # gravity-dex-monitoring-test
  # slack_api_url: "https://hooks.slack.com/services/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"

route:
  # in order to avoid continuously sending notifications for similar alerts
  # (like the same process failing on multiple instances, nodes, and data centres),
  # the Alertmanager may be configured to group these related alerts into one alert:
  group_by: ["node_exporter_metrics", "tendermint_metrics"]
  
  # how long to wait to buffer alerts of the same group before sending initially. (Usually ~0s to few minutes.)
  group_wait: 30s

  # how long to wait before sending an alert that has been added to a group which contains already fired alerts. (Usually ~5m or more.)
  group_interval: 5m

  # how long to wait before re-sending a given alert that has already been sent. (Usually ~3h or more).
  # since Gravity DEX testnet needs an immediate attention, let's give repeat_interval 15 minutes.
  repeat_interval: 15m

  # default receiver
  receiver: "alert_slack"

  routes:
    - match:
        severity: "warning"
      receiver: "alert_slack"
      
receivers:
  - name: "alert_slack"
    slack_configs:
      - send_resolved: true  
        channel: "#gravity-dex-monitoring-test"
        text: "{{ range .Alerts }}<!channel> {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

# inhibit_rules are to suppress notifications for certain alerts if other alerts are already fired
inhibit_rules:
  # Matchers for which one or more alerts have to exist for the
  # inhibition to take effect.
  - source_match:
      labelname: "InstanceDown"
      labelvalue: ["critical"]
  - source_match:
      labelname: "MemoryPoolUncommitedTxsOver10"
      labelvalue: ["warning"]
