# global block controls the Prometheus server's global configuration.
global:
  scrape_interval: 6s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

# rule_files block specifies the location of any rules we want the Prometheus server to load.
# load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'alert_rules.yml'

# A scrape configuration containing exactly one endpoint to scrape:
# scrape_configs block controls what resources Prometheus monitors.
# the job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
scrape_configs:
  ################################
  # Tendermint and Node Exporter 
  ################################
  - job_name: 'jp-s1'
    static_configs:
    - targets: ['20.0.0.9:26660','20.0.0.9:9100']
  - job_name: 'jp-s2'
    static_configs:
    - targets: ['20.0.0.11:26660',20.0.0.11:9100']
  - job_name: 'jp-s3'
    static_configs:
    - targets: ['20.0.0.26:26660','20.0.0.26:9100']
  - job_name: 'jp-s4'
    static_configs:
    - targets: ['20.0.0.30:26660','20.0.0.30:9100']
  - job_name: 'jp-s5'
    static_configs:
    - targets: ['20.0.0.14:26660','20.0.0.14:9100']
  - job_name: 'jp-s6'
    static_configs:
    - targets: ['20.0.0.5:26660','20.0.0.5:9100']
  - job_name: 'jp-s7'
    static_configs:
    - targets: ['20.0.0.27:26660','20.0.0.27:9100']
  - job_name: 'jp-s8'
    static_configs:
    - targets: ['20.0.0.24:26660','20.0.0.24:9100']
  - job_name: 'jp-v1'
    static_configs:
    - targets: ['20.0.0.4:26660','20.0.0.4:9100']
  - job_name: 'jp-v2'
    static_configs:
    - targets: ['20.0.0.20:26660','20.0.0.20:9100']
  - job_name: 'us-s1'
    static_configs:
    - targets: ['10.0.0.21:26660','10.0.0.21:9100']
  - job_name: 'us-s2'
    static_configs:
    - targets: ['10.0.0.23:26660','10.0.0.23:9100']
  - job_name: 'us-s3'
    static_configs:
    - targets: ['10.0.0.11:26660','10.0.0.11:9100']
  - job_name: 'us-s4'
    static_configs:
    - targets: ['10.0.0.4:26660','10.0.0.4:9100']
  - job_name: 'us-s5'
    static_configs:
    - targets: ['10.0.0.13:26660','10.0.0.13:9100']
  - job_name: 'us-s6'
    static_configs:
    - targets: ['10.0.0.24:26660','10.0.0.24:9100']
  - job_name: 'us-s7'
    static_configs:
    - targets: ['10.0.0.10:26660','10.0.0.10:9100']
  - job_name: 'us-s8'
    static_configs:
    - targets: ['10.0.0.26:26660','10.0.0.26:9100']
  - job_name: 'us-v1'
    static_configs:
    - targets: ['10.0.0.6:26660','10.0.0.6:9100']
  - job_name: 'us-v2'
    static_configs:
    - targets: ['10.0.0.20:26660','10.0.0.20:9100']
  - job_name: 'eu-v2'
    static_configs:
    - targets: ['30.0.0.23:26660','30.0.0.23:9100']
  - job_name: 'eu-v1'
    static_configs:
    - targets: ['30.0.0.5:26660','30.0.0.5:9100']
  - job_name: 'eu-s8'
    static_configs:
    - targets: ['30.0.0.30:26660','30.0.0.30:9100']
  - job_name: 'eu-s7'
    static_configs:
    - targets: ['30.0.0.28:26660','30.0.0.28:9100']
  - job_name: 'eu-s6'
    static_configs:
    - targets: ['30.0.0.20:26660','30.0.0.20:9100']
  - job_name: 'eu-s5'
    static_configs:
    - targets: ['30.0.0.26:26660','30.0.0.26:9100']
  - job_name: 'eu-s4'
    static_configs:
    - targets: ['30.0.0.7:26660','30.0.0.7:9100']
  - job_name: 'eu-s3'
    static_configs:
    - targets: ['30.0.0.12:26660','30.0.0.12:9100']
  - job_name: 'eu-s2'
    static_configs:
    - targets: ['30.0.0.14:26660','30.0.0.14:9100']
  - job_name: 'eu-s1'
    static_configs:
    - targets: ['30.0.0.9:26660','30.0.0.9:9100']