{
 "title": "Gravity DEX Testnet Dashboard",
 "description": "Provide an Overview over Gravity DEX Testnet Full Nodes ",
 "tags": [
  "dashboard",
  "gravity-dex-testnet",
  "prometheus",
  "grafana"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "TESTNET",
    "query": "chain_id=~\"competition-*\""
   },
   {
    "name": "NODES",
    "query": "job=\"*\""
   }
  ]
 },
 "panels": [
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Pool",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tendermint_mempool_size" }
   ]
  },
  {
   "title": "Total # Commited Tx's",
   "type": "stat",
   "description": "Total number of transactions committed",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tendermint_consensus_total_txs" }
   ]
  },
  {
   "title": "Block Height",
   "type": "singlestat",
   "description": "Height of the chain",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(tendermint_consensus_latest_block_height{$TESTNET})"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "singlestat",
   "description": "Block size in bytes",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(tendermint_consensus_block_size_bytes{$TESTNET})"
    }
   ]
  },
  {
   "title": "Number of Connected Peers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tendermint_p2p_peers{$TESTNET}", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Block TIme",
   "type": "stat",
   "description": "Time between this and last block (Block.Header.Time) in seconds\n",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(tendermint_consensus_block_interval_seconds)"
    }
   ]
  },
  {
   "title": "Total Voting Power of All Validators",
   "type": "graph",
   "description": "tendermint_consensus_validators_power Total power of all validators.",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "none", "label": "STEAK" }
   ],
   "targets": [
    {
     "expr": "min(tendermint_consensus_validators_power{$TESTNET})"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height{$TESTNET}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU 사용률",
   "type": "graph",
   "description": "각 cpu가 각 모드에서 소요한 시간을 나타내는 counter값, 라벨은 cpu, mode\n각 cpu에 대해, 모드는 초당 1초씩 증가한다. 이 값을 통해 모든 cpu에서 유휴시간(idle time)을 계산할 수 있다.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "{{job}} "
    }
   ]
  },
  {
   "title": "메모리 사용률",
   "type": "bargauge",
   "description": "# HELP node_memory_MemAvailable_bytes Memory information field MemAvailable_bytes.\n# TYPE node_memory_MemAvailable_bytes gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal - node_memory_MemAvailable) / node_memory_MemTotal) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "네트워크 입출력",
   "type": "timeseries",
   "description": "# HELP node_network_receive_bytes_total Network device statistic receive_bytes.\n# TYPE node_network_receive_bytes_total counter",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes[5m])",
     "legendFormat": "{{job}}_in - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes[5m])",
     "legendFormat": "{{job}}_out - {{device}}"
    }
   ]
  },
  {
   "title": "디스크 사용률",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - 100 * (node_filesystem_avail{device = '/dev/root'} / node_filesystem_size{device = '/dev/root'})",
     "legendFormat": "{{job}}{{mountpoint}}"
    }
   ]
  }
 ]
}